services:
  
  kurrentdb:
    image: docker.kurrent.io/kurrent-latest/kurrentdb:latest
    container_name: kurrentdb
    environment:
      - KURRENTDB_INSECURE=true
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
    ports:
      - "2113:2113"
      - "1113:1113"
    networks:
      - shopping

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: shopping
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - shopping

networks:
  shopping:
    driver: bridge
